//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegister
    {
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentContactNo { get; set; }
        public System.DateTime StudentRegisterDate { get; set; }
        public string StudentAddress { get; set; }
        public int DepartmentId { get; set; }
        public string StudentRegNo { get; set; }
    
        public virtual Department Department { get; set; }
    }
}
