//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversityManagementFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentResult
    {
        public int StudentResultId { get; set; }
        public string StudentRegNo { get; set; }
        public string StudentName { get; set; }
        public string StudentEmail { get; set; }
        public string StudentDepartment { get; set; }
        public int CourseId { get; set; }
        public int GradeId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual GradeLetter GradeLetter { get; set; }
    }
}
